### ISSUE TITLE
Can't build working binary

### ISSUE THREAD

**Issue by zytek** [fanhattan/etcd-backup#3]
Tried to build via gox on OSX and directly on a linux box, Go 1.4.2.

Is this due to go-etcd dependancy changes?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x402eda]

goroutine 1 [running]:
main.loadConfigFile(0xc20800a880, 0x0)
	/opt/golang/src/github.com/fanhattan/etcd-backup/config.go:77 +0x17a
main.LoadConfig(0xc20800a880, 0xc2080400f0, 0x7)
	/opt/golang/src/github.com/fanhattan/etcd-backup/config.go:47 +0x28
main.init·1()
	/opt/golang/src/github.com/fanhattan/etcd-backup/config.go:42 +0x36
main.init()
	/opt/golang/src/github.com/fanhattan/etcd-backup/restore.go:125 +0x6f

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by mzupan** [comment]
just ran into this issue. You need to use go 1.5
